import { Category, Item } from '@/types/game';

export const categories: Category[] = [
  {
    id: '1',
    name: 'Houses',
    slug: 'houses',
    icon: '🏠',
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Cars',
    slug: 'cars',
    icon: '🚗',
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Watches',
    slug: 'watches',
    icon: '⌚',
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Designer Fashion',
    slug: 'designer-fashion',
    icon: '👜',
    created_at: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Art',
    slug: 'art',
    icon: '🎨',
    created_at: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'Grocery Items',
    slug: 'grocery-items',
    icon: '🛒',
    created_at: new Date().toISOString(),
  },
  {
    id: '7',
    name: 'Electronics',
    slug: 'electronics',
    icon: '💻',
    created_at: new Date().toISOString(),
  },
  {
    id: '8',
    name: 'Sports Equipment',
    slug: 'sports-equipment',
    icon: '⚽',
    created_at: new Date().toISOString(),
  },
  {
    id: '9',
    name: 'Jewelry',
    slug: 'jewelry',
    icon: '💎',
    created_at: new Date().toISOString(),
  },
  {
    id: '10',
    name: 'Furniture',
    slug: 'furniture',
    icon: '🪑',
    created_at: new Date().toISOString(),
  },
];

export const items: Item[] = [
  // Cars
  {
    id: 'car-tesla-model-s',
    category_id: '2',
    name: 'Model S',
    brand: 'Tesla',
    price: 88000,
    currency: 'USD',
    description: 'The Tesla Model S is a groundbreaking electric luxury sedan introduced in 2012, known for its minimalist design, long range, and insane acceleration, especially in the Plaid variant.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/e/e8/2021_Tesla_Model_S_Plaid_Front.jpg'],
    metadata: {
      year: 2012,
      type: 'Luxury electric sedan',
      powertrain: 'Dual/tri-motor electric'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'car-bmw-m3',
    category_id: '2',
    name: 'M3',
    brand: 'BMW',
    price: 76000,
    currency: 'USD',
    description: 'The BMW M3 is a high-performance version of the 3 Series, blending luxury with motorsport DNA. The latest G80 model emphasizes power, agility, and controversial design with large kidney grilles.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/2/26/BMW_M3_Competition_XDrive_IMG_5294.jpg'],
    metadata: {
      year: 1986,
      type: 'Performance sports sedan',
      powertrain: 'Turbocharged inline-6'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'car-toyota-supra',
    category_id: '2',
    name: 'Supra',
    brand: 'Toyota',
    price: 45000,
    currency: 'USD',
    description: 'Revived in 2019, the fifth-gen Toyota Supra shares its platform with the BMW Z4, offering sharp handling and a sporty feel with a strong heritage from its legendary Mk4 predecessor.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/4/4a/2019_Toyota_Supra_3.0_Front.jpg'],
    metadata: {
      year: 2019,
      type: 'Two-door sports coupe',
      powertrain: 'Turbocharged inline-4 or inline-6'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'car-mercedes-s-class',
    category_id: '2',
    name: 'S-Class',
    brand: 'Mercedes-Benz',
    price: 115000,
    currency: 'USD',
    description: 'The S-Class is Mercedes-Benz\'s flagship sedan, setting industry standards in comfort, technology, and innovation. It\'s a favorite among executives and luxury buyers worldwide.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/4/4e/2021_Mercedes-Benz_S_500_4MATIC_Limousine_AMG_Line_Packages_%E2%80%93_Obsidian_Black%2C_front_left.jpg'],
    metadata: {
      year: 1972,
      type: 'Full-size luxury sedan',
      powertrain: 'Turbocharged inline-6 or V8'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'car-ford-mustang-gt',
    category_id: '2',
    name: 'Mustang GT',
    brand: 'Ford',
    price: 43000,
    currency: 'USD',
    description: 'An iconic American muscle car, the Mustang GT delivers raw power and old-school charm with a modern twist, powered by a 5.0L V8 in its latest form.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/0/04/2018_Ford_Mustang_GT_5.0_facelift.jpg'],
    metadata: {
      year: 1964,
      type: 'Muscle car coupe',
      powertrain: '5.0L V8'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'car-audi-rs6-avant',
    category_id: '2',
    name: 'RS6 Avant',
    brand: 'Audi',
    price: 125000,
    currency: 'USD',
    description: 'The Audi RS6 Avant is a family-friendly powerhouse, blending supercar performance with daily usability. It features Audi\'s Quattro AWD system and aggressive styling.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/4/45/Audi_RS6_Avant_IMG_3905.jpg'],
    metadata: {
      year: 2002,
      type: 'High-performance station wagon',
      powertrain: '4.0L twin-turbo V8'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'car-porsche-911-carrera',
    category_id: '2',
    name: '911 Carrera',
    brand: 'Porsche',
    price: 114000,
    currency: 'USD',
    description: 'The Porsche 911 is one of the most enduring and revered sports cars ever made. The Carrera variants balance daily drivability with thrilling performance and timeless design.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/7/7e/2019_Porsche_911_Carrera_4S_Coupe.jpg'],
    metadata: {
      year: 1964,
      type: 'Rear-engine sports car',
      powertrain: 'Turbocharged flat-6'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'car-lexus-lc-500',
    category_id: '2',
    name: 'LC 500',
    brand: 'Lexus',
    price: 98000,
    currency: 'USD',
    description: 'The Lexus LC 500 is a visually striking luxury coupe that pairs a naturally aspirated V8 with refined handling and rich interior craftsmanship, making it a standout GT.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/2/28/2018_Lexus_LC500_%28URZ100R%29_coupe_%282018-10-22%29_01.jpg'],
    metadata: {
      year: 2017,
      type: 'Luxury grand tourer coupe',
      powertrain: '5.0L V8 (also available as hybrid)'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'car-chevrolet-corvette-c8',
    category_id: '2',
    name: 'Corvette C8',
    brand: 'Chevrolet',
    price: 70000,
    currency: 'USD',
    description: 'The C8 Corvette marks a radical shift for the legendary nameplate, moving to a mid-engine layout to compete with European exotics while retaining its American identity and value.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/8/8d/2020_Chevrolet_Corvette_C8_IMG_2413.jpg'],
    metadata: {
      year: 2020,
      type: 'Mid-engine sports car',
      powertrain: '6.2L V8'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'car-range-rover-sport',
    category_id: '2',
    name: 'Range Rover Sport',
    brand: 'Land Rover',
    price: 92000,
    currency: 'USD',
    description: 'The Range Rover Sport offers a blend of luxury and off-road capability, with upscale interiors, strong performance, and the prestige associated with the Range Rover badge.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/6/67/Range_Rover_Sport_P400e_HSE_Dynamic_Automatic_2.0.jpg'],
    metadata: {
      year: 2005,
      type: 'Luxury SUV',
      powertrain: 'Turbocharged inline-6 or V8'
    },
    created_at: new Date().toISOString(),
  },

  // Houses
  {
    id: 'house-palace-versailles',
    category_id: '1',
    name: 'Palace of Versailles',
    brand: 'Royal Estate',
    price: 5000000000,
    currency: 'USD',
    description: 'Originally a hunting lodge, the Palace of Versailles became the seat of political power in France under Louis XIV. It\'s known for its lavish gardens, Hall of Mirrors, and role in French history.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/a/af/Versailles_Palace.jpg'],
    metadata: {
      year: 1661,
      location: 'Versailles, France',
      architecturalStyle: 'Baroque',
      type: 'Royal palace',
      size: '721,000 sq ft'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'house-white-house',
    category_id: '1',
    name: 'The White House',
    brand: 'Official Residence',
    price: 400000000,
    currency: 'USD',
    description: 'The official residence and workplace of the President of the United States. It has been the home of every U.S. president since John Adams.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/1/18/White_House_north_and_south_sides.jpg'],
    metadata: {
      year: 1800,
      location: 'Washington, D.C., USA',
      architecturalStyle: 'Neoclassical',
      type: 'Official residence',
      size: '55,000 sq ft'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'house-buckingham-palace',
    category_id: '1',
    name: 'Buckingham Palace',
    brand: 'Royal Estate',
    price: 4900000000,
    currency: 'USD',
    description: 'Buckingham Palace is the London residence and administrative headquarters of the British monarch. It\'s widely used for state occasions and royal hospitality.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/f/f3/Buckingham_Palace_from_gardens%2C_London%2C_UK_-_Diliff.jpg'],
    metadata: {
      year: 1703,
      location: 'London, United Kingdom',
      architecturalStyle: 'Neoclassical',
      type: 'Royal palace',
      size: '828,000 sq ft'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'house-fallingwater',
    category_id: '1',
    name: 'Fallingwater',
    brand: 'Frank Lloyd Wright',
    price: 10000000,
    currency: 'USD',
    description: 'Designed by Frank Lloyd Wright, Fallingwater is a masterpiece of organic architecture, built over a waterfall and blending seamlessly with its natural surroundings.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/f/f7/Fallingwater%2C_front_view.jpg'],
    metadata: {
      year: 1935,
      location: 'Pennsylvania, USA',
      architecturalStyle: 'Organic architecture',
      type: 'Private residence (now museum)',
      size: '5,300 sq ft'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'house-villa-savoye',
    category_id: '1',
    name: 'Villa Savoye',
    brand: 'Le Corbusier',
    price: 3500000,
    currency: 'USD',
    description: 'A seminal modernist house designed by Le Corbusier, Villa Savoye exemplifies the \'Five Points of Architecture\' and is a UNESCO World Heritage Site.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/e/ed/Villa_Savoye.JPG'],
    metadata: {
      year: 1931,
      location: 'Poissy, France',
      architecturalStyle: 'International Style / Modernist',
      type: 'Private villa',
      size: '4,800 sq ft'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'house-casa-batllo',
    category_id: '1',
    name: 'Casa Batlló',
    brand: 'Antoni Gaudí',
    price: 85000000,
    currency: 'USD',
    description: 'A landmark of Antoni Gaudí\'s creative genius, Casa Batlló features a skeletal, marine-inspired façade and imaginative interiors, making it a key attraction in Barcelona.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/1/1e/Casa_Batll%C3%B3%2C_Barcelona%2C_Spain_2022.jpg'],
    metadata: {
      year: 1906,
      location: 'Barcelona, Spain',
      architecturalStyle: 'Modernisme / Art Nouveau',
      type: 'Urban house',
      size: '12,000 sq ft'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'house-neuschwanstein-castle',
    category_id: '1',
    name: 'Neuschwanstein Castle',
    brand: 'Royal Castle',
    price: 250000000,
    currency: 'USD',
    description: 'Commissioned by Ludwig II of Bavaria, Neuschwanstein Castle looks like something from a fairytale. It inspired the design of Disney\'s Sleeping Beauty Castle.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/1/12/Neuschwanstein_Castle_LOC_print_rotated.jpg'],
    metadata: {
      year: 1886,
      location: 'Bavaria, Germany',
      architecturalStyle: 'Romanesque Revival / Fantasy',
      type: 'Castle',
      size: '65,000 sq ft'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'house-hearst-castle',
    category_id: '1',
    name: 'Hearst Castle',
    brand: 'Julia Morgan',
    price: 700000000,
    currency: 'USD',
    description: 'Built for newspaper magnate William Randolph Hearst, Hearst Castle is a lavish hilltop estate featuring elaborate pools, art collections, and guest houses.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/8/83/Hearst_Castle_Casa_Grande_September_2012_panorama_1.jpg'],
    metadata: {
      year: 1947,
      location: 'California, USA',
      architecturalStyle: 'Mediterranean Revival / Spanish Colonial',
      type: 'Mansion estate',
      size: '90,000 sq ft'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'house-winchester-mystery',
    category_id: '1',
    name: 'Winchester Mystery House',
    brand: 'Sarah Winchester',
    price: 75000000,
    currency: 'USD',
    description: 'Famous for its labyrinthine design and paranormal legend, this house was continuously built by Sarah Winchester in response to supposed ghostly voices.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/2/2c/Winchester_House_910.jpg'],
    metadata: {
      year: 1922,
      location: 'San Jose, California, USA',
      architecturalStyle: 'Victorian',
      type: 'Mansion',
      size: '24,000 sq ft'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'house-villa-tugendhat',
    category_id: '1',
    name: 'Villa Tugendhat',
    brand: 'Ludwig Mies van der Rohe',
    price: 2000000,
    currency: 'USD',
    description: 'Designed by Ludwig Mies van der Rohe, Villa Tugendhat is a pioneering modernist home known for its open plan, minimalist elegance, and use of luxury materials.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/e/ed/Vila_Tugendhat_-_celkov%C3%BD_pohled.jpg'],
    metadata: {
      year: 1930,
      location: 'Brno, Czech Republic',
      architecturalStyle: 'Modernist / Bauhaus',
      type: 'Private residence',
      size: '2,800 sq ft'
    },
    created_at: new Date().toISOString(),
  },

  // Watches
  {
    id: 'watch-rolex-submariner',
    category_id: '3',
    name: 'Submariner',
    brand: 'Rolex',
    price: 10400,
    currency: 'USD',
    description: 'The Rolex Submariner is an iconic diver\'s watch first released in 1953. It\'s celebrated for its water resistance (300 m), robust build, and timeless design.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/0/06/Rolex_Submariner.jpg'],
    metadata: {
      year: 1953,
      type: 'Dive watch',
      movement: 'Automatic',
      waterResistance: '300m',
      caseDiameter: '41mm'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'watch-omega-speedmaster',
    category_id: '3',
    name: 'Speedmaster Professional',
    brand: 'Omega',
    price: 5350,
    currency: 'USD',
    description: 'Famous as the \'Moonwatch\', the Speedmaster Professional was the first watch on the Moon, worn by astronauts during the Apollo missions.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/3/3f/Omega_Speedmaster_Professional.jpg'],
    metadata: {
      year: 1957,
      type: 'Chronograph',
      movement: 'Manual-wind',
      waterResistance: '50m',
      caseDiameter: '42mm'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'watch-patek-nautilus',
    category_id: '3',
    name: 'Nautilus 5711',
    brand: 'Patek Philippe',
    price: 60000,
    currency: 'USD',
    description: 'Designed by Gerald Genta, the Nautilus 5711 features a distinctive porthole-inspired case and is one of the most sought‑after watches in the world.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/8/8d/Patek_Philippe_Nautilus_5711.jpg'],
    metadata: {
      year: 1976,
      type: 'Luxury sports watch',
      movement: 'Automatic',
      waterResistance: '120m',
      caseDiameter: '40mm'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'watch-ap-royal-oak',
    category_id: '3',
    name: 'Royal Oak',
    brand: 'Audemars Piguet',
    price: 50000,
    currency: 'USD',
    description: 'Another Genta classic, the Royal Oak features an octagonal bezel, integrated bracelet, and paved the way for the luxury sports watch category.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/9/9a/Audemars_Piguet_Royal_Oak.jpg'],
    metadata: {
      year: 1972,
      type: 'Luxury sports watch',
      movement: 'Automatic',
      waterResistance: '50m',
      caseDiameter: '41mm'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'watch-tag-carrera',
    category_id: '3',
    name: 'Carrera',
    brand: 'TAG Heuer',
    price: 4500,
    currency: 'USD',
    description: 'Inspired by motor racing, the Carrera is known for its clean racing dial and functional chronograph layout.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/4/4d/TAG_Heuer_Carrera.jpg'],
    metadata: {
      year: 1963,
      type: 'Chronograph',
      movement: 'Automatic',
      waterResistance: '100m',
      caseDiameter: '39mm'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'watch-jlc-reverso',
    category_id: '3',
    name: 'Reverso',
    brand: 'Jaeger‑LeCoultre',
    price: 7450,
    currency: 'USD',
    description: 'Originally created for polo players, the Reverso flips the dial to protect it during matches. It\'s a 20th‑century Art Deco icon.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/1/11/Jaeger_LeCoultre_Reverso.jpg'],
    metadata: {
      year: 1931,
      type: 'Reversible dress watch',
      movement: 'Manual/Automatic',
      waterResistance: '30m',
      caseDiameter: '27mm x 43mm'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'watch-breitling-navitimer',
    category_id: '3',
    name: 'Navitimer',
    brand: 'Breitling',
    price: 8450,
    currency: 'USD',
    description: 'Famous for its circular slide rule bezel used by pilots, the Navitimer is a legendary instrument watch for aviation.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/7/7c/Breitling_Navitimer.jpg'],
    metadata: {
      year: 1952,
      type: 'Pilot chronograph',
      movement: 'Automatic',
      waterResistance: '30m',
      caseDiameter: '43mm'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'watch-iwc-portugieser',
    category_id: '3',
    name: 'Portugieser',
    brand: 'IWC',
    price: 9750,
    currency: 'USD',
    description: 'Originated from large marine chronometer movements, the Portugieser is celebrated for its classic, legible dial and elegant case.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/2/2b/IWC_Portugieser.jpg'],
    metadata: {
      year: 1939,
      type: 'Dress watch',
      movement: 'Automatic/manual',
      waterResistance: '30m',
      caseDiameter: '40.9mm'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'watch-seiko-prospex',
    category_id: '3',
    name: 'Prospex Diver',
    brand: 'Seiko',
    price: 450,
    currency: 'USD',
    description: 'A reliable, affordable dive watch famous for its durability, ISO certification, and value-packed specs.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/5/5c/Seiko_Prospex_SLA043.jpg'],
    metadata: {
      year: 1965,
      type: 'Dive watch',
      movement: 'Automatic',
      waterResistance: '200m',
      caseDiameter: '43mm'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'watch-nomos-tangente',
    category_id: '3',
    name: 'Tangente',
    brand: 'Nomos',
    price: 2000,
    currency: 'USD',
    description: 'Produced by Nomos Glashütte, the Tangente is minimalist, precision-made, and a standout in modern German watchmaking.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/0/08/Nomos_Tangente.jpg'],
    metadata: {
      year: 1992,
      type: 'Modern Bauhaus dress watch',
      movement: 'Manual/Automatic',
      waterResistance: '30m',
      caseDiameter: '38mm'
    },
    created_at: new Date().toISOString(),
  },

  // Designer Fashion
  {
    id: 'fashion-chanel-flap',
    category_id: '4',
    name: 'Classic Flap Bag',
    brand: 'Chanel',
    price: 8500,
    currency: 'USD',
    description: 'Timeless quilted leather flap bag designed by Coco Chanel and popularized by Karl Lagerfeld.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/3/3a/Chanel_Classic_Flap_Bag.jpg'],
    metadata: {
      year: 1955,
      type: 'Shoulder bag',
      material: 'Quilted leather',
      size: 'Medium'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'fashion-hermes-birkin',
    category_id: '4',
    name: 'Birkin',
    brand: 'Hermès',
    price: 12500,
    currency: 'USD',
    description: 'Iconic luxury handbag commissioned by Jane Birkin, known for exclusivity and high resale value.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/5/53/Herm%C3%A8s_Birkin.jpg'],
    metadata: {
      year: 1984,
      type: 'Top-handle tote',
      material: 'Leather',
      size: '35cm'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'fashion-lv-speedy',
    category_id: '4',
    name: 'Speedy 30',
    brand: 'Louis Vuitton',
    price: 1650,
    currency: 'USD',
    description: 'Classic monogram canvas bag originally created for travel and still popular today.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/4/4b/Louis_Vuitton_Speedy_30.jpg'],
    metadata: {
      year: 1930,
      type: 'Carryall bag',
      material: 'Monogram canvas',
      size: '30cm'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'fashion-gucci-marmont',
    category_id: '4',
    name: 'GG Marmont Matelassé Shoulder Bag',
    brand: 'Gucci',
    price: 2400,
    currency: 'USD',
    description: 'Quilted leather bag with signature Double G and heart interior detail.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/a/ae/Gucci_GG_Marmont.jpg'],
    metadata: {
      year: 2015,
      type: 'Shoulder bag',
      material: 'Matelassé leather',
      size: 'Small'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'fashion-prada-galleria',
    category_id: '4',
    name: 'Galleria Tote',
    brand: 'Prada',
    price: 2700,
    currency: 'USD',
    description: 'Structured Saffiano leather workhack bag named after Prada\'s original Milan flagship.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/1/13/Prada_Galleria_Tote.jpg'],
    metadata: {
      year: 2000,
      type: 'Tote bag',
      material: 'Saffiano leather',
      size: 'Medium'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'fashion-dior-lady',
    category_id: '4',
    name: 'Lady Dior',
    brand: 'Dior',
    price: 5200,
    currency: 'USD',
    description: 'Iconic cannage-stitch quilted bag favored by Princess Diana and designer Raf Simons.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/b/b0/Lady_Dior.jpg'],
    metadata: {
      year: 1995,
      type: 'Top-handle bag',
      material: 'Cannage leather',
      size: 'Medium'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'fashion-fendi-baguette',
    category_id: '4',
    name: 'Baguette',
    brand: 'Fendi',
    price: 2500,
    currency: 'USD',
    description: '"It\'s so baguette," tiny-shoulder bag trendsetter from Fendi\'s spring 1997 collection.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/9/94/Fendi_Baguette.jpg'],
    metadata: {
      year: 1997,
      type: 'Shoulder bag',
      material: 'Various',
      size: 'Regular'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'fashion-celine-luggage',
    category_id: '4',
    name: 'Luggage Tote',
    brand: 'Céline',
    price: 3000,
    currency: 'USD',
    description: 'Structured tote with winged sides and zipped front pocket—a minimalist hero bag.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/c/cd/Celine_Luggage_Tote.jpg'],
    metadata: {
      year: 2010,
      type: 'Tote bag',
      material: 'Leather',
      size: 'Mini'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'fashion-balenciaga-city',
    category_id: '4',
    name: 'City Bag',
    brand: 'Balenciaga',
    price: 1950,
    currency: 'USD',
    description: 'Rustic city satchel with motorcycle-inspired studs and soft, broken-in leather.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/7/7f/Balenciaga_City_Bag.jpg'],
    metadata: {
      year: 2001,
      type: 'Satchel',
      material: 'Leather',
      size: 'Regular'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'fashion-ysl-sac',
    category_id: '4',
    name: 'Sac de Jour',
    brand: 'Saint Laurent',
    price: 2600,
    currency: 'USD',
    description: 'Crisp, architectural tote that became a modern classic among luxury work bags.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/4/47/YSL_Sac_de_Jour.jpg'],
    metadata: {
      year: 2013,
      type: 'Structured tote',
      material: 'Leather',
      size: 'Small'
    },
    created_at: new Date().toISOString(),
  },

  // Art
  {
    id: 'art-mona-lisa',
    category_id: '5',
    name: 'Mona Lisa',
    brand: 'Leonardo da Vinci',
    price: 850000000,
    currency: 'USD',
    description: 'World-famous portrait housed in the Louvre, noted for its enigmatic smile and outstanding technique.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/6/6a/Mona_Lisa.jpg'],
    metadata: {
      year: 1503,
      artist: 'Leonardo da Vinci',
      type: 'Oil painting',
      dimensions: '77cm × 53cm',
      location: 'Louvre Museum, Paris'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'art-starry-night',
    category_id: '5',
    name: 'Starry Night',
    brand: 'Vincent van Gogh',
    price: 100000000,
    currency: 'USD',
    description: 'One of the most iconic Post‑Impressionist works, depicting swirling night sky over Saint‑Rémy.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/e/ea/Starry_Night.jpg'],
    metadata: {
      year: 1889,
      artist: 'Vincent van Gogh',
      type: 'Oil painting',
      dimensions: '73.7cm × 92.1cm',
      location: 'MoMA, New York'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'art-persistence-memory',
    category_id: '5',
    name: 'The Persistence of Memory',
    brand: 'Salvador Dalí',
    price: 150000000,
    currency: 'USD',
    description: 'Famous for its melting clocks motif, this painting symbolizes the fluidity of time.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/d/dd/The_Persistence_of_Memory.jpg'],
    metadata: {
      year: 1931,
      artist: 'Salvador Dalí',
      type: 'Surrealist painting',
      dimensions: '24cm × 33cm',
      location: 'MoMA, New York'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'art-girl-pearl',
    category_id: '5',
    name: 'Girl with a Pearl Earring',
    brand: 'Johannes Vermeer',
    price: 30000000,
    currency: 'USD',
    description: 'Known as the \'Mona Lisa of the North\', the painting captures a girl\'s transient expression.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/d/d7/Meisje_met_de_parel.jpg'],
    metadata: {
      year: 1665,
      artist: 'Johannes Vermeer',
      type: 'Oil painting',
      dimensions: '44.5cm × 39cm',
      location: 'Mauritshuis, The Hague'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'art-the-scream',
    category_id: '5',
    name: 'The Scream',
    brand: 'Edvard Munch',
    price: 120000000,
    currency: 'USD',
    description: 'One of the most recognizable images of existential angst in art history.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/f/f4/The_Scream.jpg'],
    metadata: {
      year: 1893,
      artist: 'Edvard Munch',
      type: 'Expressionist painting',
      dimensions: '91cm × 73.5cm',
      location: 'National Gallery, Oslo'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'art-guernica',
    category_id: '5',
    name: 'Guernica',
    brand: 'Pablo Picasso',
    price: 200000000,
    currency: 'USD',
    description: 'Powerful political statement against war, depicting the bombing of Guernica during the Spanish Civil War.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/7/74/Picasso_Guernica.jpg'],
    metadata: {
      year: 1937,
      artist: 'Pablo Picasso',
      type: 'Mural‑sized oil painting',
      dimensions: '349.3cm × 776.6cm',
      location: 'Museo Reina Sofía, Madrid'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'art-the-kiss',
    category_id: '5',
    name: 'The Kiss',
    brand: 'Gustav Klimt',
    price: 100000000,
    currency: 'USD',
    description: 'Icon of Viennese Secession style, celebrated for its decorative richness and intimate subject.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/7/71/Gustav_Klimt_016.jpg'],
    metadata: {
      year: 1908,
      artist: 'Gustav Klimt',
      type: 'Oil and gold leaf painting',
      dimensions: '180cm × 180cm',
      location: 'Österreichische Galerie Belvedere, Vienna'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'art-american-gothic',
    category_id: '5',
    name: 'American Gothic',
    brand: 'Grant Wood',
    price: 12000000,
    currency: 'USD',
    description: 'Iconic depiction of Midwestern American rural life, featuring a stern farmer and daughter.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/7/78/Grant_Wood_American_Gothic.jpg'],
    metadata: {
      year: 1930,
      artist: 'Grant Wood',
      type: 'Oil painting',
      dimensions: '78cm × 65.3cm',
      location: 'Art Institute of Chicago'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'art-birth-venus',
    category_id: '5',
    name: 'The Birth of Venus',
    brand: 'Sandro Botticelli',
    price: 100000000,
    currency: 'USD',
    description: 'Early Renaissance masterpiece celebrating mythological beauty and classical ideals.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/1/1f/Sandro_Botticelli_-_La_nascita_di_Venere.jpg'],
    metadata: {
      year: 1486,
      artist: 'Sandro Botticelli',
      type: 'Tempera on canvas',
      dimensions: '172.5cm × 278.9cm',
      location: 'Uffizi Gallery, Florence'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'art-night-watch',
    category_id: '5',
    name: 'The Night Watch',
    brand: 'Rembrandt',
    price: 500000000,
    currency: 'USD',
    description: 'Renowned for its dramatic use of light and shadow and dynamic group composition.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/2/2b/Rembrandt_-_De_Nachtwacht.jpg'],
    metadata: {
      year: 1642,
      artist: 'Rembrandt',
      type: 'Militia portrait',
      dimensions: '363cm × 437cm',
      location: 'Rijksmuseum, Amsterdam'
    },
    created_at: new Date().toISOString(),
  },

  // Grocery Items
  {
    id: 'grocery-bananas',
    category_id: '6',
    name: 'Bananas',
    brand: 'Fresh Produce',
    price: 2,
    currency: 'USD',
    description: 'High‑potassium fruit, great for snacks, smoothies, and baking.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/4/4c/Bananas.jpg'],
    metadata: {
      category: 'Fruit',
      unit: '3.5 lbs bunch',
      organic: false
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'grocery-milk',
    category_id: '6',
    name: 'Whole Milk',
    brand: 'Dairy Fresh',
    price: 3.50,
    currency: 'USD',
    description: 'Standard dairy milk with full milk fat—used for drinking, cooking, and baking.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/a/a7/Glass_of_Milk.jpg'],
    metadata: {
      category: 'Dairy',
      unit: 'Gallon',
      fatContent: '3.25%'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'grocery-brown-rice',
    category_id: '6',
    name: 'Brown Rice',
    brand: 'Grain Valley',
    price: 5,
    currency: 'USD',
    description: 'Whole‑grain rice rich in fiber and nutrition; good staple for meals.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/6/60/Brown_rice.jpg'],
    metadata: {
      category: 'Grains',
      unit: '4 lb bag',
      type: 'Long grain'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'grocery-eggs',
    category_id: '6',
    name: 'Eggs (Dozen)',
    brand: 'Farm Fresh',
    price: 2,
    currency: 'USD',
    description: 'Farm‑fresh chicken eggs—protein‑rich and versatile for cooking and baking.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/7/71/Chicken_eggs.jpg'],
    metadata: {
      category: 'Dairy',
      unit: 'Dozen',
      size: 'Large'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'grocery-olive-oil',
    category_id: '6',
    name: 'Olive Oil (1 L)',
    brand: 'Mediterranean Gold',
    price: 10,
    currency: 'USD',
    description: 'Extra‑virgin olive oil, cold‑pressed, ideal for dressings and low‑temp cooking.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/6/6b/Olive_oil.jpg'],
    metadata: {
      category: 'Cooking oil',
      unit: 'Liter',
      type: 'Extra virgin'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'grocery-broccoli',
    category_id: '6',
    name: 'Broccoli',
    brand: 'Fresh Produce',
    price: 3,
    currency: 'USD',
    description: 'Green cruciferous vegetable high in vitamins, fiber, and antioxidants.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/0/03/Broccoli_and_cross_section_edit.jpg'],
    metadata: {
      category: 'Vegetable',
      unit: '1.5 lbs',
      organic: false
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'grocery-chicken-breast',
    category_id: '6',
    name: 'Chicken Breast',
    brand: 'Premium Poultry',
    price: 12,
    currency: 'USD',
    description: 'Boneless, skinless chicken breast—lean protein staple for many diets.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/4/4d/Chicken_breast.jpg'],
    metadata: {
      category: 'Meat',
      unit: '3 lbs',
      type: 'Boneless, skinless'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'grocery-wheat-bread',
    category_id: '6',
    name: 'Whole Wheat Bread',
    brand: 'Bakery Fresh',
    price: 2.50,
    currency: 'USD',
    description: '100% whole‑grain bread with fiber and nutrients; good for sandwiches and toasts.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/c/c2/Whole_wheat_bread.jpg'],
    metadata: {
      category: 'Bakery',
      unit: 'Loaf',
      slices: 20
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'grocery-greek-yogurt',
    category_id: '6',
    name: 'Greek Yogurt (32 oz)',
    brand: 'Dairy Delight',
    price: 4,
    currency: 'USD',
    description: 'Protein‑rich thick yogurt, good for snacks, cooking, or smoothies.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/5/55/Greek_yogurt.jpg'],
    metadata: {
      category: 'Dairy',
      unit: '32 oz tub',
      fatContent: '2%'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'grocery-almonds',
    category_id: '6',
    name: 'Almonds (1 lb)',
    brand: 'Nut Valley',
    price: 8,
    currency: 'USD',
    description: 'Raw or roasted almonds—heart‑healthy snack and cooking ingredient.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/9/92/Almonds.jpg'],
    metadata: {
      category: 'Nuts',
      unit: 'Pound',
      type: 'Raw'
    },
    created_at: new Date().toISOString(),
  },

  // Electronics
  {
    id: 'electronics-iphone-14',
    category_id: '7',
    name: 'iPhone 14 Pro',
    brand: 'Apple',
    price: 999,
    currency: 'USD',
    description: 'Flagship iPhone with ProMotion display, A16 chip, and advanced camera system.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/3/30/IPhone_14_Pro.jpg'],
    metadata: {
      year: 2022,
      type: 'Smartphone',
      storage: '256GB',
      display: '6.1-inch OLED'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'electronics-samsung-s23',
    category_id: '7',
    name: 'Galaxy S23 Ultra',
    brand: 'Samsung',
    price: 1199,
    currency: 'USD',
    description: 'High-end Android phone with 200MP camera, S Pen support, and large AMOLED display.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/8/8f/Samsung_Galaxy_S23_Ultra.jpg'],
    metadata: {
      year: 2023,
      type: 'Smartphone',
      storage: '512GB',
      display: '6.8-inch AMOLED'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'electronics-dell-xps',
    category_id: '7',
    name: 'XPS 13',
    brand: 'Dell',
    price: 999,
    currency: 'USD',
    description: 'Compact, premium laptop with InfinityEdge display and Intel Evo certification.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/4/45/Dell_XPS_13.jpg'],
    metadata: {
      year: 2021,
      type: 'Laptop ultrabook',
      processor: 'Intel Core i5',
      ram: '8GB'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'electronics-sony-wh1000xm5',
    category_id: '7',
    name: 'WH‑1000XM5',
    brand: 'Sony',
    price: 399,
    currency: 'USD',
    description: 'Top-tier ANC headphones with excellent sound quality and comfort.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/2/27/Sony_WH-1000XM5.jpg'],
    metadata: {
      year: 2022,
      type: 'Noise‑cancelling headphones',
      batteryLife: '30 hours',
      driver: '30mm'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'electronics-macbook-pro',
    category_id: '7',
    name: 'MacBook Pro 14" M3',
    brand: 'Apple',
    price: 1999,
    currency: 'USD',
    description: 'Newest MacBook Pro featuring Apple\'s M3 chip—performance boost and battery life.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/1/1c/MacBook_Pro_14_M3.jpg'],
    metadata: {
      year: 2023,
      type: 'Laptop',
      processor: 'Apple M3',
      ram: '16GB'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'electronics-gopro-hero12',
    category_id: '7',
    name: 'HERO12 Black',
    brand: 'GoPro',
    price: 499,
    currency: 'USD',
    description: 'Compact, rugged camera for capturing 5.3K video in extreme conditions.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/6/6e/GoPro_HERO12_Black.jpg'],
    metadata: {
      year: 2023,
      type: 'Action camera',
      video: '5.3K60',
      waterproof: '10m'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'electronics-sony-a7-iv',
    category_id: '7',
    name: 'A7 IV',
    brand: 'Sony',
    price: 2499,
    currency: 'USD',
    description: 'Full-frame camera balancing resolution, video prowess, and autofocus speed.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/9/9f/Sony_A7_IV.jpg'],
    metadata: {
      year: 2021,
      type: 'Mirrorless camera',
      sensor: '33MP Full-frame',
      video: '4K60'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'electronics-nintendo-switch',
    category_id: '7',
    name: 'Switch OLED',
    brand: 'Nintendo',
    price: 349,
    currency: 'USD',
    description: 'Improved Nintendo Switch model featuring an OLED screen and better audio.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/0/0e/Nintendo_Switch_OLED.jpg'],
    metadata: {
      year: 2021,
      type: 'Hybrid gaming console',
      display: '7-inch OLED',
      storage: '64GB'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'electronics-apple-watch',
    category_id: '7',
    name: 'Watch Series 9',
    brand: 'Apple',
    price: 399,
    currency: 'USD',
    description: 'Latest Apple Watch offering faster performance and enhanced health tracking.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/d/d0/Apple_Watch_Series_9.jpg'],
    metadata: {
      year: 2023,
      type: 'Smartwatch',
      display: '41mm OLED',
      batteryLife: '18 hours'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'electronics-amazon-echo',
    category_id: '7',
    name: 'Echo (5th Gen)',
    brand: 'Amazon',
    price: 99,
    currency: 'USD',
    description: 'Voice‑controlled smart speaker with Alexa support and improved sound quality.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/7/79/Amazon_Echo_5th_Gen.jpg'],
    metadata: {
      year: 2023,
      type: 'Smart speaker',
      speaker: '3-inch woofer',
      connectivity: 'Wi-Fi, Bluetooth'
    },
    created_at: new Date().toISOString(),
  },

  // Sports Equipment
  {
    id: 'sports-wilson-basketball',
    category_id: '8',
    name: 'Evolution Basketball',
    brand: 'Wilson',
    price: 60,
    currency: 'USD',
    description: 'Popular composite leather basketball used at high‑school level for its grip and feel.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/3/30/Wilson_Evolution.jpg'],
    metadata: {
      sport: 'Basketball',
      type: 'Indoor/outdoor',
      size: 'Official',
      material: 'Composite leather'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'sports-titleist-pro-v1',
    category_id: '8',
    name: 'Pro V1 Golf Ball',
    brand: 'Titleist',
    price: 55,
    currency: 'USD',
    description: 'Tour‑level golf ball known for consistent flight and soft feel.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/5/57/Titleist_Pro_V1.jpg'],
    metadata: {
      sport: 'Golf',
      type: 'Golf ball',
      quantity: 'Dozen',
      compression: 'Mid'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'sports-callaway-driver',
    category_id: '8',
    name: 'Paradym Driver',
    brand: 'Callaway',
    price: 549,
    currency: 'USD',
    description: 'High‑performance titanium driver with adjustable weighting and forgiveness.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/6/6c/Callaway_Paradym_Driver.jpg'],
    metadata: {
      sport: 'Golf',
      type: 'Driver (club)',
      loft: '10.5°',
      shaft: 'Graphite'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'sports-nike-mercurial',
    category_id: '8',
    name: 'Mercurial Superfly FG',
    brand: 'Nike',
    price: 275,
    currency: 'USD',
    description: 'Elite football boot known for lightweight design and traction.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/2/2c/Nike_Mercurial_Superfly.jpg'],
    metadata: {
      sport: 'Soccer',
      type: 'Firm‑ground cleats',
      weight: '200g',
      material: 'Flyknit'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'sports-adidas-predator',
    category_id: '8',
    name: 'Predator Elite',
    brand: 'Adidas',
    price: 320,
    currency: 'USD',
    description: 'Control‑focused boot with textured zones for ball manipulation.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/b/b5/Adidas_Predator_Elite.jpg'],
    metadata: {
      sport: 'Soccer',
      type: 'Firm‑ground cleats',
      weight: '220g',
      material: 'Fusionskin'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'sports-yonex-astrox',
    category_id: '8',
    name: 'Astrox 99 Badminton Racket',
    brand: 'Yonex',
    price: 249,
    currency: 'USD',
    description: 'High‑end racket favored for power‑oriented play and head‑heavy feel.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/a/a5/Yonex_Astrox_99.jpg'],
    metadata: {
      sport: 'Badminton',
      type: 'Racket',
      weight: '88g',
      flex: 'Stiff'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'sports-rogue-barbell',
    category_id: '8',
    name: 'Echo Barbell',
    brand: 'Rogue',
    price: 265,
    currency: 'USD',
    description: 'Durable multipurpose barbell used in strength and Olympic lifting gyms.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/9/9d/Rogue_Echo_Barbell.jpg'],
    metadata: {
      sport: 'Weightlifting',
      type: 'Center knurl',
      weight: '20 kg',
      length: '2.2m'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'sports-wilson-tennis',
    category_id: '8',
    name: 'Championship Tennis Ball (3‑pack)',
    brand: 'Wilson',
    price: 5,
    currency: 'USD',
    description: 'Economical and consistent‑quality tennis balls suitable for recreational play.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/1/10/Wilson_Championship_Tennis_Balls.jpg'],
    metadata: {
      sport: 'Tennis',
      type: 'Pressurized ball',
      quantity: '3-pack',
      surface: 'All court'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'sports-spalding-nba',
    category_id: '8',
    name: 'NBA Official Game Basketball',
    brand: 'Spalding',
    price: 125,
    currency: 'USD',
    description: 'Made of full-grain leather and used in professional play.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/7/7c/Spalding_NBA_Official.jpg'],
    metadata: {
      sport: 'Basketball',
      type: 'Official game ball',
      size: 'Size 7',
      material: 'Full-grain leather'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'sports-proform-treadmill',
    category_id: '8',
    name: 'Carbon T7 Treadmill',
    brand: 'ProForm',
    price: 799,
    currency: 'USD',
    description: 'Folding treadmill with motorized incline, cushioned deck, and touchscreen display.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/4/43/ProForm_Carbon_T7.jpg'],
    metadata: {
      sport: 'Running / Fitness',
      type: 'Home treadmill',
      motor: '2.6 CHP',
      maxSpeed: '10 mph'
    },
    created_at: new Date().toISOString(),
  },

  // Jewelry
  {
    id: 'jewelry-cartier-love',
    category_id: '9',
    name: 'Love Bracelet',
    brand: 'Cartier',
    price: 6300,
    currency: 'USD',
    description: 'Iconic screw‑locked bracelet symbolizing eternal love (needs screwdriver to open).',
    images: ['https://upload.wikimedia.org/wikipedia/commons/1/18/Cartier_Love_Bracelet.jpg'],
    metadata: {
      type: 'Bangle',
      material: '18k gold',
      width: '6.1mm',
      closure: 'Screw system'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'jewelry-tiffany-solitaire',
    category_id: '9',
    name: 'Solitaire Diamond Ring',
    brand: 'Tiffany & Co.',
    price: 9500,
    currency: 'USD',
    description: 'Signature Tiffany setting lifts the diamond for maximum brilliance and visibility.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/3/31/Tiffany_Solitaire_Ring.jpg'],
    metadata: {
      type: 'Engagement ring',
      material: 'Platinum and diamond',
      carat: '1.0ct',
      cut: 'Round brilliant'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'jewelry-harry-winston',
    category_id: '9',
    name: 'Cluster Earrings',
    brand: 'Harry Winston',
    price: 12000,
    currency: 'USD',
    description: 'Elegant cluster design featuring multiple brilliant-cut diamonds.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/4/4a/Harry_Winston_Earrings.jpg'],
    metadata: {
      type: 'Stud earrings',
      material: 'Diamonds and platinum',
      totalCarat: '2.0ct',
      backType: 'Push back'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'jewelry-van-cleef',
    category_id: '9',
    name: 'Alhambra Necklace',
    brand: 'Van Cleef & Arpels',
    price: 3200,
    currency: 'USD',
    description: 'Signature quatre‑foil motif necklace, symbolizing luck and elegance.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/6/65/Van_Cleef_Alhambra_Necklace.jpg'],
    metadata: {
      type: 'Pendant necklace',
      material: 'Mother‑of‑pearl and gold',
      length: '16 inches',
      motifSize: '15mm'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'jewelry-bvlgari-serpenti',
    category_id: '9',
    name: 'Serpenti Watch‑Bracelet',
    brand: 'Bvlgari',
    price: 8500,
    currency: 'USD',
    description: 'Serpentine-themed wraparound design combining high jewelry and timepiece.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/9/9c/Bulgari_Serpenti.jpg'],
    metadata: {
      type: 'Watch-bracelet hybrid',
      material: 'Gold and diamonds',
      movement: 'Quartz',
      wraps: 'Double spiral'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'jewelry-chopard-happy',
    category_id: '9',
    name: 'Happy Diamonds Ring',
    brand: 'Chopard',
    price: 5800,
    currency: 'USD',
    description: 'Features moving diamonds inside transparent casing for playful sparkle.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/5/5d/Chopard_Happy_Diamonds_Ring.jpg'],
    metadata: {
      type: 'Ring',
      material: 'Gold and free-moving diamonds',
      movingDiamonds: 7,
      size: 'Adjustable'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'jewelry-tiffany-victoria',
    category_id: '9',
    name: 'Victoria Vine Bracelet',
    brand: 'Tiffany & Co.',
    price: 7200,
    currency: 'USD',
    description: 'Delicate vine motif bracelet with mixed-cut diamonds.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/0/08/Tiffany_Victoria_Bracelet.jpg'],
    metadata: {
      type: 'Bracelet',
      material: 'Vine‑inspired design in gold and diamonds',
      length: '7 inches',
      totalCarat: '1.5ct'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'jewelry-graff-butterfly',
    category_id: '9',
    name: 'Butterfly Brooch',
    brand: 'Graff',
    price: 95000,
    currency: 'USD',
    description: 'High‑jewelry butterfly design encrusted with colored diamonds.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/a/ab/Graff_Butterfly_Brooch.jpg'],
    metadata: {
      type: 'Brooch',
      material: 'Platinum and colored diamonds',
      wingspan: '3 inches',
      totalCarat: '8.5ct'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'jewelry-boucheron-quatre',
    category_id: '9',
    name: 'Quatre Classique Ring',
    brand: 'Boucheron',
    price: 4800,
    currency: 'USD',
    description: 'Signature quatre‑spirals band combining multiple metals and pavé diamonds.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/3/34/Boucheron_Quatre_Ring.jpg'],
    metadata: {
      type: 'Ring',
      material: 'Gold and diamonds',
      width: '8mm',
      patterns: 4
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'jewelry-piaget-possession',
    category_id: '9',
    name: 'Possession Necklace',
    brand: 'Piaget',
    price: 6000,
    currency: 'USD',
    description: 'Elegant pendant that spins within a fixed ring—symbolizing joy and elegance.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/7/7d/Piaget_Possession_Necklace.jpg'],
    metadata: {
      type: 'Rotating pendant necklace',
      material: 'Gold',
      length: '17 inches',
      pendantSize: '20mm'
    },
    created_at: new Date().toISOString(),
  },

  // Furniture
  {
    id: 'furniture-eames-lounge',
    category_id: '10',
    name: 'Eames Lounge Chair',
    brand: 'Charles & Ray Eames',
    price: 5295,
    currency: 'USD',
    description: 'Iconic mid‑century chair with molded plywood and leather—designed for ultimate comfort.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/7/7a/Eames_Lounge_Chair.jpg'],
    metadata: {
      designer: 'Charles & Ray Eames',
      year: 1956,
      type: 'Lounge chair',
      material: 'Plywood and leather'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'furniture-barcelona-chair',
    category_id: '10',
    name: 'Barcelona Chair',
    brand: 'Mies van der Rohe',
    price: 6500,
    currency: 'USD',
    description: 'Modernist classic created for the German Pavilion at the Barcelona World\'s Fair.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/8/87/Barcelona_Chair.jpg'],
    metadata: {
      designer: 'Mies van der Rohe & Lilly Reich',
      year: 1929,
      type: 'Occasional chair',
      material: 'Steel and leather'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'furniture-noguchi-table',
    category_id: '10',
    name: 'Noguchi Coffee Table',
    brand: 'Isamu Noguchi',
    price: 3250,
    currency: 'USD',
    description: 'Organic sculptural table featuring a curved wood base and tempered glass top.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/4/4d/Noguchi_Coffee_Table.jpg'],
    metadata: {
      designer: 'Isamu Noguchi',
      year: 1944,
      type: 'Coffee table',
      material: 'Wood and glass'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'furniture-lc2-chair',
    category_id: '10',
    name: 'LC2 Petit Comfort Chair',
    brand: 'Le Corbusier',
    price: 4800,
    currency: 'USD',
    description: 'Icon of 20th‑century modernism with geometric steel frame and plush cushions.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/5/51/Le_Corbusier_LC2_Chair.jpg'],
    metadata: {
      designer: 'Le Corbusier, Pierre Jeanneret, Charlotte Perriand',
      year: 1928,
      type: 'Armchair',
      material: 'Chrome steel and leather'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'furniture-egg-chair',
    category_id: '10',
    name: 'Egg Chair',
    brand: 'Arne Jacobsen',
    price: 6400,
    currency: 'USD',
    description: 'Sculptural chair with enveloping form—designed for the SAS Royal Hotel in Copenhagen.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/3/38/Egg_Chair.jpg'],
    metadata: {
      designer: 'Arne Jacobsen',
      year: 1958,
      type: 'Lounge chair',
      material: 'Fiberglass and fabric'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'furniture-wassily-chair',
    category_id: '10',
    name: 'Wassily Chair',
    brand: 'Marcel Breuer',
    price: 2800,
    currency: 'USD',
    description: 'Bauhaus classic using tubular steel and leather straps—built for the modern home.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/c/c6/Wassily_Chair.jpg'],
    metadata: {
      designer: 'Marcel Breuer',
      year: 1925,
      type: 'Armchair',
      material: 'Tubular steel and leather'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'furniture-wishbone-chair',
    category_id: '10',
    name: 'Wishbone Chair',
    brand: 'Hans Wegner',
    price: 600,
    currency: 'USD',
    description: 'Iconic Danish chair with curved wooden frame and woven seat.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/6/6e/Wegner_Wishbone_Chair.jpg'],
    metadata: {
      designer: 'Hans Wegner',
      year: 1949,
      type: 'Dining chair',
      material: 'Wood and paper cord'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'furniture-tolix-chair',
    category_id: '10',
    name: 'Tolix Marais A Chair',
    brand: 'Xavier Pauchard',
    price: 290,
    currency: 'USD',
    description: 'Industrial-style metal chair popular in cafés and bistros worldwide.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/2/23/Tolix_Chair.jpg'],
    metadata: {
      designer: 'Xavier Pauchard',
      year: 1934,
      type: 'Steel café chair',
      material: 'Galvanized steel'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'furniture-arco-lamp',
    category_id: '10',
    name: 'Arco Floor Lamp',
    brand: 'Castiglioni Brothers',
    price: 2500,
    currency: 'USD',
    description: 'Overhanging marble-base lamp—an elegant blend of form and engineering.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/1/15/Flos_Arco_Lamp.jpg'],
    metadata: {
      designer: 'Achille & Pier Giacomo Castiglioni',
      year: 1962,
      type: 'Floor lamp',
      material: 'Marble and steel'
    },
    created_at: new Date().toISOString(),
  },
  {
    id: 'furniture-ikea-poang',
    category_id: '10',
    name: 'Poäng Armchair',
    brand: 'Ikea',
    price: 79,
    currency: 'USD',
    description: 'Comfortable, affordable bentwood armchair with wide popularity.',
    images: ['https://upload.wikimedia.org/wikipedia/commons/0/08/Ikea_Poang.jpg'],
    metadata: {
      designer: 'Redesign in 1976 (original 1970)',
      type: 'Armchair',
      material: 'Bentwood and fabric',
      weight: '15 kg'
    },
    created_at: new Date().toISOString(),
  },
];